services:
  orca-dummy-agent:
    container_name: orca-dummy-agent
    build: .
    volumes:
      - .:/app
    ports:
      - 8005:80
    env_file: .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orca-dummy.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.docker.network=traefik-network"
    networks:
      - traefik-network
      - postgres-network

networks:
  traefik-network:
    external: true
  postgres-network:
    external: true
